version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
