version: '3.9'
services:
  app:
    build: .
    env_file: default.env
    depends_on:
      - postgres
    volumes:
      - ./src/dbcp:/app/dbcp:ro
      - ./notebooks:/app/notebooks:rw
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - ./test:/app/test:r
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    command: jupyter lab --port ${JUPYTER_PORT} --ip 0.0.0.0 --no-browser
  postgres:
    image: postgis/postgis:13-3.1-alpine
    env_file: default.env
    ports:
      - ${POSTGRES_PORT}:5432
