services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - API_KEY_GOOGLE_MAPS=${API_KEY_GOOGLE_MAPS} # get this value from our google account: https://console.cloud.google.com/google/maps-apis/credentials?project=dbcp-dev&supportedpurview=project
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/dbcp:/app/dbcp:rw
      - ./notebooks:/app/notebooks:rw
      - ./data:/app/data:rw
      - ./test:/app/test:ro
      - ${GOOGLE_GHA_CREDS_PATH}:/app/gcloud_application_default_credentials.json:ro
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    command: jupyter lab --port ${JUPYTER_PORT} --ip 0.0.0.0 --no-browser

  postgres:
    image: postgis/postgis:13-3.1-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 5s
      timeout: 5s
      retries: 5
