services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - API_KEY_GOOGLE_MAPS=${API_KEY_GOOGLE_MAPS} # get this value from our google account: https://console.cloud.google.com/google/maps-apis/credentials?project=dbcp-dev&supportedpurview=project
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - GEOCODIO_API_KEY=${GEOCODIO_API_KEY} # This api key is stored GCP project secret manager as geocodio-api-key
      - PROD_POSTGRES_USER=${PROD_POSTGRES_USER}
      - PROD_POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
      - PROD_POSTGRES_HOST=${PROD_POSTGRES_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/dbcp:/app/dbcp:rw
      - ./src/scripts:/app/scripts:rw
      - ./notebooks:/app/notebooks:rw
      - ./data:/app/data:rw
      - ./test:/app/test:rw
      - ${GOOGLE_GHA_CREDS_PATH}:/app/gcloud_application_default_credentials.json:ro
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    command: jupyter lab --port ${JUPYTER_PORT} --ip 0.0.0.0 --no-browser

  postgres:
    image: postgis/postgis:13-3.1-alpine
    env_file:
      - .env
    ports:
      - ${DEV_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
