[flake8]
# A few linter errors and warnings that we are currently ignoring:
# * W503, W504: Line break before / after binary operator.
# * D401: Imperative mood.
# * E501: Overlong line
ignore = W503,W504,D401,E501
inline-quotes = double
max-line-length = 88
# Files and directories that should be subject to linting
extend-exclude =
    package_data,
    .env_pudl,
    .eggs,
    build,
# We have a backlog of complex functions being skipped with noqa: C901
max-complexity = 10
format = ${cyan}%(path)s${reset}:${green}%(row)-4d${reset} ${red_bold}%(code)s${reset} %(text)s
extend-ignore =
# Google Python style is not RST until after processed by Napoleon
# See https://github.com/peterjc/flake8-rst-docstrings/issues/17
    RST201,RST203,RST301,
rst-roles =
    attr,
    class,
    doc,
    func,
    meth,
    mod,
    obj,
    py:const,
    ref,
    user,
rst-directives =
    envvar,
    exception,
percent-greedy = 2
format-greedy = 2
