[project]
site_name = "Deployment Gap Model"
site_description = ""

repo_url = "https://github.com/deployment-gap-model-education-fund/deployment-gap-model"
repo_name = "deployment-gap-model-education-fund/deployment-gap-model"

[[project.nav]]
title = "Overview"
path = "index.md"

[[project.nav]]
title = "Data Sources"
path = "data_sources.md"

[[project.nav]]
title = "Tables"

[[project.nav.items]]
title = "Data Warehouse"
items = [
  { title = "Overview", path = "data-warehouse/README.md" },
  { title = "acp__private__changelog__projects", path = "data-warehouse/acp__private__changelog__projects.md" },
  { title = "acp__private__projects", path = "data-warehouse/acp__private__projects.md" },
  { title = "airtable__association__offshore_wind_cable_landing", path = "data-warehouse/airtable__association__offshore_wind_cable_landing.md" },
  { title = "airtable__manual_ordinances", path = "data-warehouse/airtable__manual_ordinances.md" },
  { title = "airtable__offshore_wind_locations", path = "data-warehouse/airtable__offshore_wind_locations.md" },
  { title = "airtable__offshore_wind_port_association", path = "data-warehouse/airtable__offshore_wind_port_association.md" },
  { title = "airtable__offshore_wind_projects", path = "data-warehouse/airtable__offshore_wind_projects.md" },
  { title = "airtable__offshore_wind_staging_association", path = "data-warehouse/airtable__offshore_wind_staging_association.md" },
  { title = "census__county_fips", path = "data-warehouse/census__county_fips.md" },
  { title = "census__state_fips", path = "data-warehouse/census__state_fips.md" },
  { title = "columbia_reldi_local_opposition__local_ordinance", path = "data-warehouse/columbia_reldi_local_opposition__local_ordinance.md" },
  { title = "columbia_reldi_local_opposition__state_policy", path = "data-warehouse/columbia_reldi_local_opposition__state_policy.md" },
  { title = "eia860m__annual__generators", path = "data-warehouse/eia860m__annual__generators.md" },
  { title = "_eia860m__changelog__generators", path = "data-warehouse/_eia860m__changelog__generators.md" },
  { title = "eia860m__operational_status_codes", path = "data-warehouse/eia860m__operational_status_codes.md" },
  { title = "eip_facilities", path = "data-warehouse/eip_facilities.md" },
  { title = "fyi__private__locations", path = "data-warehouse/fyi__private__locations.md" },
  { title = "fyi__private__projects", path = "data-warehouse/fyi__private__projects.md" },
  { title = "fyi__private__resource_capacity", path = "data-warehouse/fyi__private__resource_capacity.md" },
  { title = "madrone__data_last_updated", path = "data-warehouse/madrone__data_last_updated.md" },
  { title = "ncsl__state_permitting", path = "data-warehouse/ncsl__state_permitting.md" },
]

[[project.nav.items]]
title = "Data Mart"
items = [
  { title = "Overview", path = "data-mart/README.md" },
  { title = "eia860m__generators_operational_status_transition_dates", path = "data-mart/eia860m__generators_operational_status_transition_dates.md" },
  { title = "eia860m__latest__generators", path = "data-mart/eia860m__latest__generators.md" },
  { title = "eia860m__latest__plants", path = "data-mart/eia860m__latest__plants.md" },
  { title = "eia860m__monthly__generators", path = "data-mart/eia860m__monthly__generators.md" },
  { title = "fyi__private__counties__active_clean_projects_capacity", path = "data-mart/fyi__private__counties__active_clean_projects_capacity.md" },
]

[[project.nav.items]]
title = "Deployment Metadata"
path = "deployment_metadata.md"

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  # "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  # "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]


[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"


[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}
