"""SQL Alchemy metadata for the datawarehouse tables."""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    ForeignKeyConstraint,
    Integer,
    MetaData,
    String,
    Table,
)

metadata = MetaData()
schema = "private_data_warehouse"

##############
# ACP Tables #
##############
acp_changelog = Table(
    "acp_changelog",
    metadata,
    Column("proj_id", BigInteger, primary_key=True),
    Column("report_date", DateTime, primary_key=True),
    Column("valid_until_date", DateTime),
    Column("status", String),
    Column("plant_id_eia", Integer),
    Column("project_name", String),
    Column("phase_name", String),
    Column("resource", String),
    Column("developers", String),
    Column("owners", String),
    Column("iso_region", String),
    Column("owner_types", String),
    Column("capacity_mw", Float),
    Column("state_id_fips", String),
    Column("county_id_fips", String),
    Column("avg_latitude", Float),
    Column("avg_longitude", Float),
    Column("geocoded_locality_name", String),
    Column("geocoded_locality_type", String),
    Column("geocoded_containing_county", String),
    Column("geocoded_county_id_fips", String),
    Column("geocoded_state_id_fips", String),
    Column("census_county_id_fips", String),
    Column("raw_mw_total_capacity", Float),
    Column("raw_units_total", String),
    Column("raw_mw_online_capacity", String),
    Column("raw_mw_under_construction_capacity", Float),
    Column("raw_mw_adv_development_capacity", Float),
    Column("raw_mw_decommissioned_capacity", Float),
    Column("raw_units_online", Integer),
    Column("raw_units_under_construction", Integer),
    Column("raw_units_adv_development", Integer),
    Column("raw_units_decommissioned", Integer),
    Column("raw_years_online", String),
    Column("raw_quarters_online", String),
    Column("raw_countries", String),
    Column("raw_states", String),
    Column("raw_counties", String),
    Column("raw_community", Boolean),
    Column("raw_repower_type", String),
    Column("raw_repower_phases", String),
    Column("raw_owner_types", String),
    Column("raw_constructors", String),
    Column("raw_servicers", String),
    Column("raw_manufacturers", String),
    Column("raw_models", String),
    Column("raw_hub_heights", String),
    Column("raw_rotor_diameters", String),
    Column("raw_total_heights", String),
    Column("raw_avg_latitude", String),
    Column("raw_avg_longitude", String),
    Column("raw_offtake_types", String),
    Column("raw_power_purchasers", String),
    Column("raw_power_purchaser_types", String),
    Column("raw_power_purchaser_type_details", String),
    Column("raw_ppa_rates", String),
    Column("raw_ppa_start_years", String),
    Column("raw_ppa_end_years", String),
    Column("raw_ppa_durations", String),
    Column("raw_interconnected_utilities", String),
    Column("raw_iso_rtos", String),
    Column("raw_nercs", String),
    Column("raw_balancing_authorities", String),
    Column("raw_state_houses", String),
    Column("raw_state_senates", String),
    Column("raw_congressional_districts", String),
    Column("raw_secondary_offtake_types", String),
    Column("raw_secondary_purchaser_ids", String),
    Column("raw_secondary_purchaser_types", String),
    Column("raw_tracking_types", String),
    Column("raw_ilrs", Float),
    Column("raw_nameplate_mws", String),
    Column("raw_storage_energies", String),
    Column("raw_storage_durations", String),
    schema=schema,
)

acp_projects_current = Table(
    "acp_projects_current",
    metadata,
    Column("proj_id", BigInteger, primary_key=True),
    Column("report_date", DateTime),
    Column("status", String),
    Column("plant_id_eia", Integer),
    Column("project_name", String),
    Column("phase_name", String),
    Column("resource", String),
    Column("developers", String),
    Column("owners", String),
    Column("iso_region", String),
    Column("owner_types", String),
    Column("capacity_mw", Float),
    Column("state_id_fips", String),
    Column("county_id_fips", String),
    Column("avg_latitude", Float),
    Column("avg_longitude", Float),
    Column("geocoded_locality_name", String),
    Column("geocoded_locality_type", String),
    Column("geocoded_containing_county", String),
    Column("geocoded_county_id_fips", String),
    Column("geocoded_state_id_fips", String),
    Column("census_county_id_fips", String),
    Column("raw_mw_total_capacity", Float),
    Column("raw_units_total", String),
    Column("raw_mw_online_capacity", String),
    Column("raw_mw_under_construction_capacity", Float),
    Column("raw_mw_adv_development_capacity", Float),
    Column("raw_mw_decommissioned_capacity", Float),
    Column("raw_units_online", Integer),
    Column("raw_units_under_construction", Integer),
    Column("raw_units_adv_development", Integer),
    Column("raw_units_decommissioned", Integer),
    Column("raw_years_online", String),
    Column("raw_quarters_online", String),
    Column("raw_countries", String),
    Column("raw_states", String),
    Column("raw_counties", String),
    Column("raw_community", Boolean),
    Column("raw_repower_type", String),
    Column("raw_repower_phases", String),
    Column("raw_owner_types", String),
    Column("raw_constructors", String),
    Column("raw_servicers", String),
    Column("raw_manufacturers", String),
    Column("raw_models", String),
    Column("raw_hub_heights", String),
    Column("raw_rotor_diameters", String),
    Column("raw_total_heights", String),
    Column("raw_avg_latitude", String),
    Column("raw_avg_longitude", String),
    Column("raw_offtake_types", String),
    Column("raw_power_purchasers", String),
    Column("raw_power_purchaser_types", String),
    Column("raw_power_purchaser_type_details", String),
    Column("raw_ppa_rates", String),
    Column("raw_ppa_start_years", String),
    Column("raw_ppa_end_years", String),
    Column("raw_ppa_durations", String),
    Column("raw_interconnected_utilities", String),
    Column("raw_iso_rtos", String),
    Column("raw_nercs", String),
    Column("raw_balancing_authorities", String),
    Column("raw_state_houses", String),
    Column("raw_state_senates", String),
    Column("raw_congressional_districts", String),
    Column("raw_secondary_offtake_types", String),
    Column("raw_secondary_purchaser_ids", String),
    Column("raw_secondary_purchaser_types", String),
    Column("raw_tracking_types", String),
    Column("raw_ilrs", Float),
    Column("raw_nameplate_mws", String),
    Column("raw_storage_energies", String),
    Column("raw_storage_durations", String),
    schema=schema,
)

######################################
# Interconnection.fyi Project Queues #
######################################
fyi_projects = Table(
    "fyi_projects",
    metadata,
    Column("project_id", String, primary_key=True, autoincrement=False),
    Column("project_type", String),
    Column("power_market", String, nullable=False),
    Column("transmission_owner", String),
    Column("developer", String),
    Column("developer_raw", String),
    Column("canonical_transmission_owners", String),
    Column("interconnection_status_fyi", String),
    Column("interconnection_status_raw", String),
    Column("queue_id", String),
    Column("project_name", String),
    Column("actual_completion_date", DateTime, nullable=True),
    Column("proposed_completion_date", DateTime, nullable=True),
    Column("withdrawn_date", DateTime, nullable=True),
    Column("queue_date", DateTime),
    Column("queue_year", Integer),
    Column("county_state_pairs", String),
    Column("point_of_interconnection", String),
    Column("canonical_generation_types", String),
    Column("interconnection_service_type", String),
    Column("interconnection_date", DateTime),
    Column("interconnection_date_raw", String),
    Column("queue_status", String, nullable=False),
    Column("summer_capacity_mw", Float),
    Column("winter_capacity_mw", Float),
    Column("current_phase_or_stage_raw", String),
    Column("project_spv", String),
    Column("utility", String),
    Column("iso", String),
    Column("cluster", String),
    Column("general_comments", String),
    Column("interconnection_voltage_kv", String),
    Column("latitude", Float),
    Column("longitude", Float),
    Column("schedule_next_event_date", DateTime),
    Column("schedule_next_event_name", String),
    Column("most_recent_study_date", DateTime),
    Column("most_recent_study_url", String),
    Column("most_recent_allocated_network_upgrade_cost", Float),
    Column("is_actionable", Boolean),
    Column("is_nearly_certain", Boolean),
    schema=schema,
)

fyi_locations = Table(
    "fyi_locations",
    metadata,
    Column(
        "project_id",
        String,
        ForeignKey("private_data_warehouse.fyi_projects.project_id"),
    ),
    Column("raw_county_name", String),
    Column("raw_state_name", String),
    Column(
        "state_id_fips",
        String,
        nullable=True,
    ),
    Column(
        "county_id_fips",
        String,
        nullable=True,
    ),
    Column("geocoded_locality_name", String),
    Column("geocoded_locality_type", String),
    Column("geocoded_containing_county", String),
    ForeignKeyConstraint(
        ["state_id_fips"],
        ["data_warehouse.state_fips.state_id_fips"],
        link_to_name=True,
    ),
    ForeignKeyConstraint(
        ["county_id_fips"],
        ["data_warehouse.county_fips.county_id_fips"],
        link_to_name=True,
    ),
    schema=schema,
)


fyi_resource_capacity = Table(
    "fyi_resource_capacity",
    metadata,
    Column(
        "project_id",
        String,
        ForeignKey("private_data_warehouse.fyi_projects.project_id"),
    ),
    Column("resource", String),
    Column("resource_clean", String),
    Column("capacity_mw", Float),
    schema=schema,
)
