"""SQL Alchemy models for the data mart tables."""
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    MetaData,
    String,
    Table,
)

metadata = MetaData()
schema = "data_mart"

counties_wide_format = Table(
    "counties_wide_format",
    metadata,
    Column("state_id_fips", String),
    Column("county_id_fips", String, primary_key=True),
    Column("state", String, nullable=True),
    Column("county", String),
    Column("has_ordinance", Boolean),
    Column("state_permitting_type", String, nullable=True),
    Column("county_total_co2e_tonnes_per_year", Float, nullable=True),
    Column("fossil_existing_capacity_mw", Float, nullable=True),
    Column("fossil_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("fossil_existing_facility_count", Integer, nullable=True),
    Column("fossil_proposed_capacity_mw", Float, nullable=True),
    Column("fossil_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("fossil_proposed_facility_count", Integer, nullable=True),
    Column("renewable_and_battery_existing_capacity_mw", Float, nullable=True),
    Column("renewable_and_battery_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("renewable_and_battery_existing_facility_count", Integer, nullable=True),
    Column("renewable_and_battery_proposed_capacity_mw", Float, nullable=True),
    Column("renewable_and_battery_proposed_facility_count", Integer, nullable=True),
    Column("infra_total_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("infra_total_proposed_facility_count", Integer, nullable=True),
    Column("infra_total_proposed_nox_tonnes_per_year", Float, nullable=True),
    Column("infra_total_proposed_pm2_5_tonnes_per_year", Float, nullable=True),
    Column("battery_storage_existing_capacity_mw", Float, nullable=True),
    Column("battery_storage_existing_facility_count", Integer, nullable=True),
    Column("battery_storage_proposed_capacity_mw", Float, nullable=True),
    Column("battery_storage_proposed_facility_count", Integer, nullable=True),
    Column("coal_existing_capacity_mw", Float, nullable=True),
    Column("coal_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("coal_existing_facility_count", Integer, nullable=True),
    Column("coal_proposed_capacity_mw", Float, nullable=True),
    Column("coal_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("coal_proposed_facility_count", Integer, nullable=True),
    Column("gas_existing_capacity_mw", Float, nullable=True),
    Column("gas_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("gas_existing_facility_count", Integer, nullable=True),
    Column("gas_proposed_capacity_mw", Float, nullable=True),
    Column("gas_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("gas_proposed_facility_count", Integer, nullable=True),
    Column("offshore_wind_existing_capacity_mw", Float, nullable=True),
    Column("offshore_wind_existing_facility_count", Integer, nullable=True),
    Column("offshore_wind_proposed_capacity_mw", Float, nullable=True),
    Column("offshore_wind_proposed_facility_count", Integer, nullable=True),
    Column("oil_existing_capacity_mw", Float, nullable=True),
    Column("oil_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("oil_existing_facility_count", Integer, nullable=True),
    Column("onshore_wind_existing_capacity_mw", Float, nullable=True),
    Column("onshore_wind_existing_facility_count", Integer, nullable=True),
    Column("onshore_wind_proposed_capacity_mw", Float, nullable=True),
    Column("onshore_wind_proposed_facility_count", Integer, nullable=True),
    Column("solar_existing_capacity_mw", Float, nullable=True),
    Column("solar_existing_co2e_tonnes_per_year", Float, nullable=True),
    Column("solar_existing_facility_count", Integer, nullable=True),
    Column("solar_proposed_capacity_mw", Float, nullable=True),
    Column("solar_proposed_facility_count", Integer, nullable=True),
    Column("infra_gas_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("infra_gas_proposed_facility_count", Integer, nullable=True),
    Column("infra_gas_proposed_nox_tonnes_per_year", Float, nullable=True),
    Column("infra_gas_proposed_pm2_5_tonnes_per_year", Float, nullable=True),
    Column("infra_lng_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("infra_lng_proposed_facility_count", Integer, nullable=True),
    Column("infra_lng_proposed_nox_tonnes_per_year", Float, nullable=True),
    Column("infra_lng_proposed_pm2_5_tonnes_per_year", Float, nullable=True),
    Column("infra_oil_proposed_co2e_tonnes_per_year", Float, nullable=True),
    Column("infra_oil_proposed_facility_count", Integer, nullable=True),
    Column("infra_oil_proposed_nox_tonnes_per_year", Float, nullable=True),
    Column("infra_oil_proposed_pm2_5_tonnes_per_year", Float, nullable=True),
    Column(
        "infra_petrochemicals_and_plastics_proposed_co2e_tonnes_per_year",
        Float,
        nullable=True,
    ),
    Column(
        "infra_petrochemicals_and_plastics_proposed_facility_count",
        Integer,
        nullable=True,
    ),
    Column(
        "infra_petrochemicals_and_plastics_proposed_nox_tonnes_per_year",
        Float,
        nullable=True,
    ),
    Column(
        "infra_petrochemicals_and_plastics_proposed_pm2_5_tonnes_per_yea",
        Float,
        nullable=True,
    ),
    Column(
        "infra_synthetic_fertilizers_proposed_co2e_tonnes_per_year",
        Float,
        nullable=True,
    ),
    Column(
        "infra_synthetic_fertilizers_proposed_facility_count", Integer, nullable=True
    ),
    Column(
        "infra_synthetic_fertilizers_proposed_nox_tonnes_per_year", Float, nullable=True
    ),
    Column(
        "infra_synthetic_fertilizers_proposed_pm2_5_tonnes_per_year",
        Float,
        nullable=True,
    ),
    Column("ordinance", String, nullable=True),
    Column("ordinance_earliest_year_mentioned", Float, nullable=True),
    Column("ordinance_jurisdiction_name", String, nullable=True),
    Column("ordinance_jurisdiction_type", String, nullable=True),
    Column("state_permitting_text", String, nullable=True),
    schema=schema,
)

existing_plants = Table(
    "existing_plants",
    metadata,
    Column("plant_id_eia", Integer, primary_key=True),
    Column("resource", String),
    Column("max_operating_date", DateTime, nullable=True),
    Column("capacity_mw", Float),
    Column("co2e_tonnes_per_year", Float, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column("county_id_fips", String, nullable=True),
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    schema=schema,
)

fossil_infrastructure_projects = Table(
    "fossil_infrastructure_projects",
    metadata,
    Column("project_id", Integer, primary_key=True),
    Column("project_name", String),
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("county_id_fips", String, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column("latitude", Float, nullable=True),
    Column("longitude", Float, nullable=True),
    Column("raw_street_address", String, nullable=True),
    Column("air_construction_id", Float, nullable=True),
    Column("facility_id", Integer, nullable=True),
    Column("facility_name", String, nullable=True),
    Column("project_classification", String, nullable=True),
    Column("industry_sector", String),
    Column("raw_project_type", String),
    Column("project_description", String, nullable=True),
    Column("facility_description", String, nullable=True),
    Column("permit_description", String, nullable=True),
    Column("cost_millions", Integer, nullable=True),
    Column("raw_number_of_jobs_promised", String, nullable=True),
    Column("date_modified", DateTime),
    Column("co2e_tonnes_per_year", Float, nullable=True),
    Column("voc_tonnes_per_year", Float, nullable=True),
    Column("so2_tonnes_per_year", Float, nullable=True),
    Column("nox_tonnes_per_year", Float, nullable=True),
    Column("co_tonnes_per_year", Float, nullable=True),
    Column("pm2_5_tonnes_per_year", Float, nullable=True),
    Column("total_wetlands_affected_permanently_acres", Float, nullable=True),
    Column("total_wetlands_affected_temporarily_acres", String, nullable=True),
    Column("raw_estimated_population_within_3_miles", Integer, nullable=True),
    Column("raw_percent_low_income_within_3_miles", Float, nullable=True),
    Column("raw_percent_people_of_color_within_3_miles", Float, nullable=True),
    Column("raw_respiratory_hazard_index_within_3_miles", Float, nullable=True),
    Column("raw_relative_cancer_risk_per_million_within_3_miles", Float, nullable=True),
    Column("raw_wastewater_discharge_indicator", Float, nullable=True),
    Column("is_ally_target", String),
    schema=schema,
)

iso_projects_wide_format = Table(
    "iso_projects_wide_format",
    metadata,
    Column("project_id", Integer, primary_key=True),
    Column("project_name", String, nullable=True),
    Column("iso_region", String),
    Column("entity", String),
    Column("utility", String, nullable=True),
    Column("developer", String, nullable=True),
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column("county_id_fips", String, nullable=True),
    Column("resource_class", String, nullable=True),
    Column("is_hybrid", Boolean),
    Column("generation_type_1", String, nullable=True),
    Column("generation_capacity_mw_1", Float, nullable=True),
    Column("generation_type_2", String, nullable=True),
    Column("generation_capacity_mw_2", Float, nullable=True),
    Column("storage_type", String, nullable=True),
    Column("storage_capacity_mw", Float, nullable=True),
    Column("co2e_tonnes_per_year", Float),
    Column("date_entered_queue", DateTime, nullable=True),
    Column("date_proposed_online", DateTime, nullable=True),
    Column("interconnection_status", String),
    Column("point_of_interconnection", String, nullable=True),
    Column("queue_status", String),
    Column("has_ordinance", Boolean),
    Column("ordinance_jurisdiction_name", String, nullable=True),
    Column("ordinance_jurisdiction_type", String, nullable=True),
    Column("ordinance_earliest_year_mentioned", Integer, nullable=True),
    Column("ordinance", String, nullable=True),
    Column("state_permitting_type", String, nullable=True),
    schema=schema,
)
iso_projects_long_format = Table(
    "iso_projects_long_format",
    metadata,
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("project_id", Integer, primary_key=True),
    Column("date_proposed_online", DateTime, nullable=True),
    Column("developer", String, nullable=True),
    Column("entity", String),
    Column("interconnection_status", String),
    Column("point_of_interconnection", String, nullable=True),
    Column("project_name", String, nullable=True),
    Column("date_entered_queue", DateTime, nullable=True),
    Column("queue_status", String),
    Column("iso_region", String),
    Column("utility", String, nullable=True),
    Column("capacity_mw", Float, nullable=True),
    Column("resource_clean", String, primary_key=True),
    Column("state_id_fips", String, nullable=True),
    Column("county_id_fips", String, nullable=True),
    Column("state_permitting_type", String, nullable=True),
    Column("co2e_tonnes_per_year", Float, nullable=True),
    Column("ordinance_earliest_year_mentioned", Float, nullable=True),
    Column("ordinance_jurisdiction_name", String, nullable=True),
    Column("ordinance_jurisdiction_type", String, nullable=True),
    Column("ordinance", String, nullable=True),
    Column("has_ordinance", Boolean),
    Column("is_hybrid", Boolean),
    Column("resource_class", String, nullable=True),
    schema=schema,
)

proposed_power_dash_existing_plants = Table(
    "proposed_power_dash_existing_plants",
    metadata,
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column(
        "county_id_fips", String, nullable=True
    ),  # Should be a part of the primary key, 9 records with missing count info
    Column("resource", String),  # Should be a part of the primary key
    Column("capacity_mw", Float),
    Column("permitting_type", String, nullable=True),
    Column("has_ordinance", Boolean),
    schema=schema,
)

proposed_power_dash_proposed_plants = Table(
    "proposed_power_dash_proposed_plants",
    metadata,
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column(
        "county_id_fips", String, nullable=True
    ),  # Should be a part of the primary key, 9 records with missing count info
    Column(
        "resource", String
    ),  # Should be a part of the primary key, 9 records missing resource info
    Column("capacity_mw", Float, nullable=True),
    Column("project_count", Integer),
    Column("permitting_type", String, nullable=True),
    Column("has_ordinance", Boolean),
    schema=schema,
)

proposed_power_dash_local_opp = Table(
    "proposed_power_dash_local_opp",
    metadata,
    Column("county_id_fips", String, primary_key=True),
    Column("ordinance_earliest_year_mentioned", Integer, nullable=True),
    Column("ordinance_jurisdiction_name", String),
    Column("ordinance_jurisdiction_type", String),
    Column("ordinance", String),
    Column("has_ordinance", Boolean),
    Column("state_id_fips", String),
    Column("county", String),
    Column("state", String),
    Column("state_abbrev", String),
    Column("permitting_type", String, nullable=True),
    schema=schema,
)

co2_dashboard = Table(
    "co2_dashboard",
    metadata,
    Column("state", String, nullable=True),
    Column("county", String, nullable=True),
    Column("state_id_fips", String, nullable=True),
    Column(
        "id", Integer, nullable=True
    ),  # Should be a part of the pk but is missing one value :(
    Column("county_id_fips", String, nullable=True),
    Column("co2e_tonnes_per_year", Float, nullable=True),
    Column("facility_type", String),  # Should be a part of the pk
    schema=schema,
)

counties_long_format = Table(
    "counties_long_format",
    metadata,
    Column("state_id_fips", String),
    Column("county_id_fips", String, primary_key=True),
    Column("state", String),
    Column("county", String),
    Column("facility_type", String, primary_key=True),
    Column("resource_or_sector", String, primary_key=True),
    Column("status", String, primary_key=True),
    Column("facility_count", Integer),
    Column("capacity_mw", Float, nullable=True),
    Column("co2e_tonnes_per_year", Float, nullable=True),
    Column("pm2_5_tonnes_per_year", Float, nullable=True),
    Column("nox_tonnes_per_year", Float, nullable=True),
    Column("has_ordinance", Boolean),
    Column("ordinance_jurisdiction_name", String, nullable=True),
    Column("ordinance_jurisdiction_type", String, nullable=True),
    Column("ordinance", String, nullable=True),
    Column("ordinance_earliest_year_mentioned", Integer, nullable=True),
    Column("state_permitting_type", String, nullable=True),
    Column("state_permitting_text", String),
    schema=schema,
)
