"""
Extract gridstatus iso queues data from private bucket archive.

gridstatus code points directly at interconnection queue spreadsheets
on ISO queues websites. These spreadsheets can change without notice
and break the gridstatus API. We have a private archive of the gridstatus data
that allows us to pin the ETL code to a specific version of the raw
data. The version numbers are automatically generated by Google Cloud Storage
Object Versioning.
"""
import logging

import pandas as pd

import dbcp

logger = logging.getLogger(__name__)

ISO_QUEUE_VERSIONS: dict[str, str] = {
    "miso": "1695410266348973",
    "caiso": "1695410268849071",
    "pjm": "1688930176762145",
    "ercot": "1695410271245243",
    "spp": "1695410273744495",
    "nyiso": "1695410276215338",
    "isone": "1695410278762236",
}


def extract():
    """Extract gridstatus ISO Queue data."""
    iso_queues: dict[str, pd.DataFrame] = {}
    credentials = dbcp.extract.helpers.get_gcp_credentials()
    for iso, revision_num in ISO_QUEUE_VERSIONS.items():
        uri = f"gs://gridstatus-archive/interconnection_queues/{iso}.parquet"
        path = dbcp.extract.helpers.cache_gcs_archive_file_locally(
            uri=uri, revision_num=revision_num, credentials=credentials
        )

        iso_queues[iso] = pd.read_parquet(path)

    return iso_queues
