name: Docker Image CI

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker compose build
      env:
        JUPYTER_PORT: 8888
        POSTGRES_PORT: 5432
        ENV_FILE: default.env

