---
name: pytest

on:
  push:
    branches:
      - version-outputs # for testing only

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
      API_KEY_EIA: ${{ secrets.API_KEY_EIA }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display workspace directory
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE"

      - name: Give the dbcp user ownership of the workspace
        run: sudo chown -R 1000:1000 $GITHUB_WORKSPACE

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose services
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          make test

      - name: Stop Docker Compose services
        run: |
          docker-compose down
