---
name: full-build

on:
  push:
    branches:
      - version-outputs # for testing only

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
      API_KEY_EIA: ${{ secrets.API_KEY_EIA }}
      GOOGLE_GHA_CREDS_PATH: ${{ secrets.GOOGLE_GHA_CREDS_PATH }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.DGM_GITHUB_ACTION_CREDENTIALS }}"

      - name: Display env variables
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE" \
          echo "Google credentials path: $GOOGLE_GHA_CREDS_PATH" \

      - name: Give the dbcp user ownership of the workspace
        run: sudo chmod -R u+rwx 1000:1000 $GITHUB_WORKSPACE

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose services
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          make all_local

      - name: Stop Docker Compose services
        run: |
          docker-compose down
