---
name: update-data

on:
  push:
    branches:
      - "main"
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      target:
        description: "dev or prod"
        required: true
        default: "dev"
        type: choice
        options: [dev, prod]
      release_tag:
        description: "Release tag to deploy to prod (leave blank to use latest published release)"
        required: false
        default: ""
  schedule:
    - cron: 0 0 * * 0
  release:
    types: [published] # immediately deploy prod when a release is published

jobs:
  etl:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      GEOCODIO_API_KEY: ${{ secrets.GEOCODIO_API_KEY }}
      API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
      GITHUB_REF: ${{ github.ref_name }}
      PROD_POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
      PROD_POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
      PROD_POSTGRES_HOST: ${{ secrets.PROD_POSTGRES_HOST }}
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v7

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.DGM_GITHUB_ACTION_CREDENTIALS }}"

      - name: Display env variables
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE" \
          echo "Google credentials path: $GOOGLE_GHA_CREDS_PATH" \

      - name: Run full ETL
        if: ${{ success() }}
        run: |
          make all

      - name: Run all test
        if: ${{ success() }}
        run: |
          make test

      # Set necessary environment variables for publish step
      - name: Set upload outputs environment variables
        run: |
          {
            echo "BUILD_REF=${{ github.ref_name }}";
            echo "CODE_GIT_SHA=${{ steps.checkout.outputs.commit }}";
            echo "GITHUB_ACTION_RUN_ID=${{ github.run_id }}";
            echo "TARGET=${{ inputs.target }}";
          } >> "$GITHUB_ENV"

      # Publish the outputs, grab the git SHA of the commit step
      - name: Upload outputs
        run: |
          make upload_outputs
