---
name: update-data

on:
  push:
    branches:
      - "**"
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      target:
        description: "dev or prod"
        required: true
        default: "dev"
        type: choice
        options: [dev, prod]

jobs:
  etl:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      GEOCODIO_API_KEY: ${{ secrets.GEOCODIO_API_KEY }}
      API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
      GITHUB_REF: ${{ github.ref_name }}
      PROD_POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
      PROD_POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
      PROD_POSTGRES_HOST: ${{ secrets.PROD_POSTGRES_HOST }}
      DATA_DIR: "./data"
      PUDL_VERSION: stable
      TARGET: ${{ inputs.target || (github.ref_type == 'tag' && 'prod' || 'dev') }}
      # Only upload outputs on tag push, push to main, or manual trigger
      # Pushes to other branches will still run the ETL and tests for CI purposes
      UPLOAD: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.DGM_GITHUB_ACTION_CREDENTIALS }}"

      - name: Display env variables
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE" \
          echo "Google credentials path: $GOOGLE_GHA_CREDS_PATH" \

      - name: Run full ETL
        if: ${{ success() }}
        run: |
          make all

      - name: Run all test
        if: ${{ success() }}
        run: |
          make test

      # Set necessary environment variables for upload step
      - name: Set upload outputs environment variables
        run: |
          {
            echo "BUILD_REF=${{ github.ref_name }}";
            echo "CODE_GIT_SHA=${{ steps.checkout.outputs.commit }}";
            echo "GITHUB_ACTION_RUN_ID=${{ github.run_id }}";
          } >> "$GITHUB_ENV"

      # Publish the outputs, grab the git SHA of the commit step
      - name: Upload outputs
        if: ${{ env.UPLOAD == 'true' }}
        run: |
          make upload_outputs

      - name: Save version number associated with completed build
        if: ${{ env.UPLOAD == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: version-file
          path: version.txt
