- generation_num: 1778377893596169
  metadata:
    schema_generation_number: '1778377885607972'
    table_id: tbluX3aa4T2lhvRFv
  name: airtable/Offshore Wind Locations DBCP Version/Locations.json
  pinned: false
- generation_num: 1778377892827965
  metadata:
    schema_generation_number: '1778377885607972'
    table_id: tblVK1P1eYblnevqo
  name: airtable/Offshore Wind Locations DBCP Version/Projects.json
  pinned: false
