- generation_num: 1775671621025571
  metadata:
    schema_generation_number: '1775671619461303'
    table_id: tbluX3aa4T2lhvRFv
  name: airtable/Offshore Wind Locations DBCP Version/Locations.json
  pinned: false
- generation_num: 1775671620064293
  metadata:
    schema_generation_number: '1775671619461303'
    table_id: tblVK1P1eYblnevqo
  name: airtable/Offshore Wind Locations DBCP Version/Projects.json
  pinned: false
