- generation_num: 1774141956444326
  metadata:
    schema_generation_number: '1774141948749646'
    table_id: tbluX3aa4T2lhvRFv
  name: airtable/Offshore Wind Locations DBCP Version/Locations.json
  pinned: false
- generation_num: 1774141955775357
  metadata:
    schema_generation_number: '1774141948749646'
    table_id: tblVK1P1eYblnevqo
  name: airtable/Offshore Wind Locations DBCP Version/Projects.json
  pinned: false
